// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_88maPhpOFmcZHv2V-8LsnOXlOvgVWE',
    appId: '1:67353207769:web:4f8d83bfdbf2e6f17c6fc8',
    messagingSenderId: '67353207769',
    projectId: 'servicifyccst',
    authDomain: 'servicifyccst.firebaseapp.com',
    storageBucket: 'servicifyccst.firebasestorage.app',
    measurementId: 'G-T38N3YB1ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyJ53sQ_szfw2IAqLu-ekUeyJw4yX2xgI',
    appId: '1:67353207769:android:84f6ccd09de9ac947c6fc8',
    messagingSenderId: '67353207769',
    projectId: 'servicifyccst',
    storageBucket: 'servicifyccst.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBD9wKvQ9d60TS8Mk9ozOjtw4gC3-I854',
    appId: '1:67353207769:ios:51df6ab5f736d3787c6fc8',
    messagingSenderId: '67353207769',
    projectId: 'servicifyccst',
    storageBucket: 'servicifyccst.firebasestorage.app',
    iosBundleId: 'com.ralfiz.servicify',
  );
}
